site_name: 'CoderDojo TC Java'
nav:
  - CoderDojo TC: https://coderdojotc.github.io/CoderDojoTC/
  - Beginning Java - Repl.it:
    - Introduction: beginner/00-introduction.md
    - Objects: beginner/01-objects.md
    - Variable: trinket/03-variables.md
    - Loops: trinket/04-loops.md
    - Conditional: trinket/05-conditionals.md
    - Functions: trinket/06-functions.md
    - Flower: trinket/07-flower.md
    - Function Parameters: trinket/07-function-parameters.md
    - Lists: trinket/08-list.md
    - Random Numbers: trinket/08-random.md
    - Random Stars: trinket/13-random-stars.md
    - Input: trinket/11-input.md
    - Recursion: trinket/12-recursion.md
  - Contributing:
    - How to Contribute Examples: contribute.md
  - Contact:
    - Contact: contact.md

site_description: 'Resources for teaching Java to CoderDojo Twin Cities students.'
site_author: 'Aaron Korver'
repo_name: 'java-dojo'
repo_url: 'https://github.com/aaronkorver/java-dojo'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
markdown_extensions:
  - codehilite
